name: SignColors
main: de.codehat.signcolors.SignColors
author: CodeHat
website: https://www.spigotmc.org/resources/signcolors.6135/
softdepend: [Vault]
description: Be able to apply colors on signs.
version: 1.2.0

commands:
  sc:
    description: Shows information about SignColors.
    usage: /<command>
    aliases: [signcolors]
    
permissions:
  signcolors.*:
    description: Access to all features.
    children:
      signcolors.command.*: true
      signcolors.specialsign.*: true
      signcolors.color.all: true
      signcolors.format.all: true
      signcolors.signcrafting.bypass: true
      signcolors.blockedfirstlines.bypass: true
      signcolors.updatemessage: true
  signcolors.command.*:
    description: Access to all the plugin'a commands.
    children:
      signcolors.command.info: true
      signcolors.command.help: true
      signcolors.command.reload: true
      signcolors.command.colorcodes: true
      signcolors.command.givesign: true
      signcolors.command.migratedatabase: true
  signcolors.specialsign.*:
    description: Allows you to create and use [SC] signs.
    children:
      signcolors.specialsign.create: true
      signcolors.specialsign.use: true
  signcolors.color.all:
    description: Allows you to apply all colors on signs.
    children:
      signcolors.color.0: true
      signcolors.color.1: true
      signcolors.color.2: true
      signcolors.color.3: true
      signcolors.color.4: true
      signcolors.color.5: true
      signcolors.color.6: true
      signcolors.color.7: true
      signcolors.color.8: true
      signcolors.color.9: true
      signcolors.color.a: true
      signcolors.color.b: true
      signcolors.color.c: true
      signcolors.color.d: true
      signcolors.color.e: true
      signcolors.color.f: true
  signcolors.format.all:
    description: Allows you to apply all formats on signs.
    children:
      signcolors.color.k: true
      signcolors.color.l: true
      signcolors.color.m: true
      signcolors.color.n: true
      signcolors.color.o: true
      signcolors.color.r: true
  signcolors.command.info:
    description: Allows you to view the plugin's info.
  signcolors.command.help:
    description: Allows you to view the help page.
  signcolors.command.reload:
    description: Allows you to reload the config.yml.
  signcolors.command.colorcodes:
    description: Allows you to use the color codes command.
  signcolors.command.givesign:
    description: Allows you to use the give sign command.
  signcolors.command.migratedatabase:
    description: Allows you to migrate the database.
  signcolors.specialsign.create:
    description: Allows you to create [SC] signs.
  signcolors.specialsign.use:
    description: Allows you to use [SC] signs.
  signcolors.color.all:
    description: Allows you to apply all colors/formats on signs.
  signcolors.signcrafting.bypass:
    description: Allows you to apply colors on a normal sign, even if 'sign_crafting' is true.
  signcolors.blockedfirstlines.bypass:
    description: Allows you to bypass the blocked first lines.
  signcolors.updatemessage:
    description: Shows an update message to you upon joining the server, if an update is available.
  signcolors.color.0:
    description: Access to BLACK color.
  signcolors.color.1:
    description: Access to DARK_BLUE color.
  signcolors.color.2:
    description: Access to DARK_GREEN color.
  signcolors.color.3:
    description: Access to DARK_AQUA color.
  signcolors.color.4:
    description: Access to DARK_RED color.
  signcolors.color.5:
    description: Access to DARK_PURPLE color.
  signcolors.color.6:
    description: Access to GOLD color.
  signcolors.color.7:
    description: Access to GRAY color.
  signcolors.color.8:
    description: Access to DARK_GRAY color.
  signcolors.color.9:
    description: Access to BLUE color.
  signcolors.color.a:
    description: Access to GREEN color.
  signcolors.color.b:
    description: Access to AQUA color.
  signcolors.color.c:
    description: Access to RED color.
  signcolors.color.d:
    description: Access to LIGHT_PURPLE color.
  signcolors.color.e:
    description: Access to YELLOW color.
  signcolors.color.f:
    description: Access to WHITE color.
  signcolors.format.k:
    description: Access to MAGIC format.
  signcolors.format.l:
    description: Access to BOLD format.
  signcolors.format.m:
    description: Access to STRIKETHROUGH format.
  signcolors.format.n:
    description: Access to UNDERLINE format.
  signcolors.format.o:
    description: Access to ITALIC format.
  signcolors.format.r:
    description: Access to RESET format.