name: SignColors
main: de.codehat.signcolors.SignColors
author: CodeHat
website: https://www.spigotmc.org/resources/signcolors.6135/
softdepend: [Vault]
description: Be able to apply colors on signs.
version: 1.2.0

commands:
  sc:
    description: Shows information about SignColors.
    usage: /<command>
    aliases: [signcolors]
    
permissions:
  signcolors.*:
    description: Access to all features.
    children:
      signcolors.colors: true
      signcolors.info: true
      signcolors.help: true
      signcolors.reload: true
      signcolors.specialsign.create: true
      signcolors.specialsign.use: true
      signcolors.updatemsg: true
      signcolors.craftsigns.bypass: true
      signcolors.listcodes: true
      signcolors.givesign: true
      signcolors.blockedfirstlines.bypass: true
      signcolors.upgrade: true
  signcolors.colors:
    description: Allows you to apply all colors on signs.
  signcolors.info:
    description: Allows you to view the plugin's info.
  signcolors.help:
    description: Allows you to view the help page.
  signcolors.reload:
    description: Allows you to reload the config.yml.
  signcolors.specialsign.create:
    description: Allows you to create a [SC] sign.
  signcolors.specialsign.use:
    description: Allows you to use a [SC] sign.
  signcolors.updatemsg:
    description: Shows an update message to you upon joining the server, if an update is available.
  signcolors.craftsigns.bypass:
    description: Allows you to apply colors on a normal sign, even if 'sign_crafting' is true.
  signcolors.listcodes:
    description: Allows you to use the color codes command.
  signcolors.givesign:
    description: Allows you to use the give sign command.
  signcolors.blockedfirstlines.bypass:
    description: Allows you to bypass the blocked first lines.