name: SignColors
main: de.codehat.signcolors.SignColors
author: CodeHat
website: https://www.spigotmc.org/resources/signcolors.6135/
softdepend: [Vault]
description: Make colored signs.
version: 1.1.0

commands:
  sc:
    description: Shows information about SignColors.
    usage: /<command>
    aliases: [signcolors]
    
permissions:
  signcolors.*:
    description: Access to all features.
    children:
      signcolors.colors: true
      signcolors.info: true
      signcolors.help: true
      signcolors.reload: true
      signcolors.sign.create: true
      signcolors.sign.use: true
      signcolors.colorsymbol: true
      signcolors.updatemsg: true
      signcolors.craftsign.bypass: true
      signcolors.listcodes: true
      signcolors.givesign: true
      signcolors.blockedfirstlines.bypass: true
      signcolors.upgrade: true
  signcolors.colors:
    description: Allows you to write colored signs.
  signcolors.info:
    description: Allows you to see the SignColors info.
  signcolors.help:
    description: Allows you to see the /sc help page.
  signcolors.reload:
    description: Allows you to reload the config.yml.
  signcolors.sign.create:
    description: Allows you to create a [SignColors] sign.
    children:
      signcolors.blockedfirstlines.bypass: true
  signcolors.sign.use:
    description: Allows you to use a [SC] sign.
  signcolors.colorsymbol:
    description: Allows you to change the color symbol ingame.
  signcolors.updatemsg:
    description: Shows you the update message, if an update is available.
  signcolors.craftsign.bypass:
    description: Allows you to write colored on a normal sign, even if signcrafting is true.
  signcolors.listcodes:
    description: Allows you to use the /sc colorcodes command.
  signcolors.givesign:
    description: Allows you to use the /sc givesign command.
  signcolors.blockedfirstlines.bypass:
    description: Allows you to bypass the blocked first lines.
  signcolors.upgrade:
    description: Allows you to upgrade the database to the new format.